//! Google AdX adapter — binary protobuf wire format.
//!
//! AdX speaks a Google-specific protobuf schema (see
//! `bidder-protos/proto/adx.proto`) carried over `application/octet-stream`.
//! We decode the protobuf into the slim `bidder.adx.v1.BidRequest` message
//! generated by `prost`, then map it into the bidder's internal OpenRTB
//! `BidRequest` so the pipeline doesn't need to know about AdX-specific
//! shapes.
//!
//! What this adapter handles:
//! - Decode protobuf → internal BidRequest (id, single imp from adslot,
//!   user.id from google_user_id, site, device, geo).
//! - Encode internal BidResponse → protobuf BidResponse with one Ad per
//!   winning bid: max_cpm_micros = bid_price_cents × 10,000 (USD micros),
//!   nurl carried through, ext_json preserves bidder pCTR/score.
//!
//! What this adapter explicitly does NOT do (Phase 7 scope cut, documented
//! in docs/notes/phase-7-production-hardening.md):
//! - Hyperlocal targeting decryption (requires partnership-issued keys).
//! - Cookie matching / Google user-list reconciliation.
//! - Signed nurl template substitution (Google supplies the macros at
//!   integration time).
//!
//! These gaps mean the adapter is wire-compatible but not production-ready
//! against live AdX traffic without the Google-side credentials. Swapping
//! in the upstream `realtime-bidding.proto` and adding the crypto layer is
//! the path to a real AdX shipper.

use super::{ExchangeAdapter, ExchangeId, ResponseContentType};
use crate::model::openrtb::{BidRequest, BidResponse};
use anyhow::{Context, Result};
use bidder_protos::adx;
use prost::Message;

const RESPONSE_CONTENT_TYPE: ResponseContentType = "application/octet-stream";
const ID: ExchangeId = "google-adx";

/// Stateless. Real production AdX adapters hold per-buyer crypto keys; this
/// scaffolding does not — see module docs.
#[derive(Debug, Default, Clone, Copy)]
pub struct GoogleAdxAdapter;

impl ExchangeAdapter for GoogleAdxAdapter {
    fn id(&self) -> ExchangeId {
        ID
    }

    fn decode_request(&self, body: &mut Vec<u8>) -> Result<BidRequest> {
        let raw = adx::BidRequest::decode(body.as_slice())
            .context("adx protobuf bid request decode failed")?;
        adx_to_internal(raw)
    }

    fn encode_response(&self, response: &BidResponse) -> Result<(Vec<u8>, ResponseContentType)> {
        let proto = internal_to_adx(response);
        let mut buf = Vec::with_capacity(proto.encoded_len());
        proto
            .encode(&mut buf)
            .context("adx protobuf bid response encode failed")?;
        Ok((buf, RESPONSE_CONTENT_TYPE))
    }
}

/// AdX BidRequest → internal OpenRTB BidRequest.
///
/// We reach the internal model via `serde_json::from_value` so we don't
/// have to enumerate every optional OpenRTB field — serde fills the rest
/// from `#[serde(default)]`. This is acceptable for Phase 7 scaffolding;
/// once AdX traffic actually flows through, the hot path mapping should be
/// inlined to avoid the JSON round-trip.
fn adx_to_internal(raw: adx::BidRequest) -> Result<BidRequest> {
    let id = bytes_to_string_lossy(&raw.id);
    let user_id = raw.user.as_ref().map(|u| u.google_user_id.clone());
    let device_ua = raw.device.as_ref().map(|d| d.ua.clone());
    let device_ip = raw.device.as_ref().map(|d| d.ip.clone());
    let site_page = raw.site.as_ref().map(|s| s.url.clone());
    let site_ref = raw.site.as_ref().map(|s| s.referrer.clone());

    let (imp_id, w, h, bidfloor) = if let Some(slot) = raw.adslot.as_ref() {
        let w = slot.width.first().copied().unwrap_or(0) as i32;
        let h = slot.height.first().copied().unwrap_or(0) as i32;
        let floor_usd = slot.matching_ad_data_minimum_cpm_micros as f64 / 1_000_000.0;
        (slot.id.to_string(), w, h, floor_usd)
    } else {
        anyhow::bail!("adx bid request missing adslot");
    };

    let geo = raw.geo.as_ref().map(|g| {
        serde_json::json!({
            "country": g.country,
            "region": g.region,
            "city": g.city,
        })
    });

    // serde-driven construction. Only fields we actually populate from AdX
    // are listed; everything else falls to `#[serde(default)]`.
    let mut json = serde_json::json!({
        "id": id,
        "imp": [{
            "id": imp_id,
            "banner": { "w": w, "h": h },
            "bidfloor": bidfloor,
        }],
    });
    if let Some(uid) = user_id {
        json["user"] = serde_json::json!({ "id": uid });
    }
    if site_page.is_some() || site_ref.is_some() {
        let mut site = serde_json::Map::new();
        if let Some(p) = site_page {
            site.insert("page".into(), serde_json::Value::String(p));
        }
        if let Some(r) = site_ref {
            site.insert("ref".into(), serde_json::Value::String(r));
        }
        json["site"] = serde_json::Value::Object(site);
    }
    if device_ua.is_some() || device_ip.is_some() || geo.is_some() {
        let mut device = serde_json::Map::new();
        if let Some(ua) = device_ua {
            device.insert("ua".into(), serde_json::Value::String(ua));
        }
        if let Some(ip) = device_ip {
            device.insert("ip".into(), serde_json::Value::String(ip));
        }
        if let Some(g) = geo {
            device.insert("geo".into(), g);
        }
        json["device"] = serde_json::Value::Object(device);
    }

    serde_json::from_value(json).context("adx → internal BidRequest mapping failed")
}

/// Internal BidResponse → AdX BidResponse (single ad-slot, multiple Ads).
fn internal_to_adx(resp: &BidResponse) -> adx::BidResponse {
    let mut ads: Vec<adx::Ad> = Vec::new();
    for seatbid in &resp.seatbid {
        for bid in &seatbid.bid {
            let max_cpm_micros = (bid.price * 1_000_000.0).round() as i64;
            let buyer_creative_id = bid
                .crid
                .as_deref()
                .and_then(|s| s.parse::<u32>().ok())
                .unwrap_or(0);
            let adslot_id = bid.impid.parse::<u32>().unwrap_or(0);
            // bid.ext is set by ResponseBuildStage with bidder_pctr/score.
            // Pass through verbatim so downstream analytics can consume it.
            let ext_json = bid.ext.as_ref().map(|v| v.to_string()).unwrap_or_default();
            ads.push(adx::Ad {
                max_cpm_micros,
                buyer_creative_id,
                adslot_id,
                nurl: bid.nurl.clone().unwrap_or_default(),
                ext_json,
            });
        }
    }
    adx::BidResponse {
        id: resp.id.as_bytes().to_vec(),
        ad: ads,
    }
}

/// AdX BidRequest.id is bytes (typically 16-byte v4 UUID). The internal
/// model uses String; lossy UTF-8 is good enough for logging and metric
/// labels — the bytes are opaque to the bidder otherwise.
fn bytes_to_string_lossy(b: &[u8]) -> String {
    if let Ok(s) = std::str::from_utf8(b) {
        return s.to_string();
    }
    // Fall back to lowercase hex so the id is at least stable + comparable.
    let mut out = String::with_capacity(b.len() * 2);
    for byte in b {
        out.push_str(&format!("{:02x}", byte));
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::model::openrtb::{Bid, SeatBid};

    fn sample_request() -> adx::BidRequest {
        adx::BidRequest {
            id: b"test-req-1".to_vec(),
            adslot: Some(adx::AdSlot {
                id: 42,
                width: vec![300],
                height: vec![250],
                matching_ad_data_minimum_cpm_micros: 1_500_000,
            }),
            site: Some(adx::Site {
                url: "https://publisher.example.com/article".to_string(),
                referrer: "https://google.com".to_string(),
            }),
            mobile: None,
            user: Some(adx::User {
                google_user_id: "user-abc".to_string(),
            }),
            geo: Some(adx::Geo {
                country: "US".to_string(),
                region: "CA".to_string(),
                city: "SF".to_string(),
            }),
            device: Some(adx::Device {
                ua: "Mozilla/5.0".to_string(),
                ip: "1.2.3.4".to_string(),
            }),
        }
    }

    #[test]
    fn id_is_stable() {
        assert_eq!(GoogleAdxAdapter.id(), "google-adx");
    }

    #[test]
    fn decode_protobuf_round_trips_to_internal() {
        let mut buf = Vec::with_capacity(sample_request().encoded_len());
        sample_request().encode(&mut buf).unwrap();
        let req = GoogleAdxAdapter
            .decode_request(&mut buf)
            .expect("decode adx request");
        assert_eq!(req.id, "test-req-1");
        assert_eq!(req.imp.len(), 1);
        assert_eq!(req.imp[0].id, "42");
        assert_eq!(req.imp[0].banner.as_ref().unwrap().w, Some(300));
        assert_eq!(req.user.as_ref().unwrap().id.as_deref(), Some("user-abc"));
        // 1_500_000 micros = $1.50.
        assert!((req.imp[0].bidfloor.unwrap() - 1.5).abs() < 1e-6);
    }

    #[test]
    fn decode_returns_error_on_invalid_protobuf() {
        let mut body = b"not a protobuf payload at all".to_vec();
        assert!(GoogleAdxAdapter.decode_request(&mut body).is_err());
    }

    #[test]
    fn decode_returns_error_when_adslot_missing() {
        let req = adx::BidRequest {
            id: b"r".to_vec(),
            adslot: None,
            site: None,
            mobile: None,
            user: None,
            geo: None,
            device: None,
        };
        let mut buf = Vec::with_capacity(req.encoded_len());
        req.encode(&mut buf).unwrap();
        assert!(GoogleAdxAdapter.decode_request(&mut buf).is_err());
    }

    #[test]
    fn encode_produces_octet_stream_with_one_ad() {
        let response = BidResponse {
            id: "req-99".to_string(),
            seatbid: vec![SeatBid {
                bid: vec![Bid {
                    id: "bid-1".into(),
                    impid: "7".into(),
                    price: 2.5,
                    nurl: Some("https://bid.example.com/win?token=...".into()),
                    crid: Some("100".into()),
                    cid: Some("42".into()),
                    adid: Some("100".into()),
                    burl: None,
                    lurl: None,
                    adm: None,
                    adomain: None,
                    bundle: None,
                    iurl: None,
                    tactic: None,
                    cat: vec![],
                    attr: vec![],
                    api: None,
                    protocol: None,
                    qagmediarating: None,
                    language: None,
                    dealid: None,
                    w: None,
                    h: None,
                    wratio: None,
                    hratio: None,
                    exp: None,
                    ext: Some(serde_json::json!({"bidder_pctr": 0.42})),
                }],
                seat: None,
                group: 0,
                ext: None,
            }],
            bidid: None,
            cur: Some("USD".into()),
            customdata: None,
            nbr: None,
            ext: None,
        };
        let (body, ct) = GoogleAdxAdapter.encode_response(&response).unwrap();
        assert_eq!(ct, "application/octet-stream");
        let decoded = adx::BidResponse::decode(body.as_slice()).expect("decode adx response");
        assert_eq!(decoded.ad.len(), 1);
        assert_eq!(decoded.ad[0].max_cpm_micros, 2_500_000);
        assert_eq!(decoded.ad[0].buyer_creative_id, 100);
        assert_eq!(decoded.ad[0].adslot_id, 7);
        assert!(decoded.ad[0].nurl.contains("token="));
        assert!(decoded.ad[0].ext_json.contains("bidder_pctr"));
    }
}
